---
title: Plot embeddings from python
author: Molly Lewis 
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    number_sections: false
    theme: cerulean
    toc_float: true
    code_folding: show 
---

******
******


```{r setup, include = F}
# load packages
library(knitr)
library(rmarkdown)
library(broom)
library(tidyverse) 
library(ggplot2)
library(stringr)

opts_chunk$set(echo = T, message = F, warning = F, 
               error = F, cache = F, tidy = F, fig.height = 4)
```  

### Read in data 
```{r}
p1_young= read.csv("/Documents/GRADUATE_SCHOOL/Projects/next_kids/experiments/nextKids_pilot1/data/next/3-4yo/participant_data_34.csv") %>%
  mutate(exp = 1, 
         age_group = "young")
p1_mid= read.csv("/Documents/GRADUATE_SCHOOL/Projects/next_kids/experiments/nextKids_pilot1/data/next/5-6yo/participant_data_56.csv") %>%
  mutate(exp = 1,
         age_group = "mid")
p2_young= read.csv("/Documents/GRADUATE_SCHOOL/Projects/next_kids/experiments/nextKids_pilot2/data/3-4yo/participant_data_34.csv") %>%
  mutate(exp = 2,
         age_group = "young")
p2_mid= read.csv("/Documents/GRADUATE_SCHOOL/Projects/next_kids/experiments/nextKids_pilot2/data/5-6yo/participant_data_56.csv") %>%
  mutate(exp = 2,
         age_group = "mid")
```

### Merge and munge
```{r}
d = rbind(p1_young, p1_mid, p2_young, p2_mid) %>%
    #filter(alg_id == "UncertaintySampling") %>%
    select(exp, age_group, target_center, target_left, target_right, target_winner) %>%
    mutate_each(funs(lapply(str_split(., ".com/|.jpg"), 
                                   function(x) {x[2]})), -exp, -age_group)  %>%
    mutate_each(funs(as.factor(unlist(.))),-exp, -age_group)

d = d %>%
    mutate(i = target_center,
           j = ifelse(target_left == target_winner, as.character(target_right), as.character(target_left)),
           k = target_winner)
```

### Convert names to numeric (for python)
```{r}
images = unique(d$i)
image_dict = data.frame(images = images, image_num = 0:(length(images)-1))

d_numeric = d %>%
  select(exp, age_group, i, j, k) %>%
  left_join(image_dict, by=c("i"="images")) %>%
  select(-i) %>%
  rename(i = image_num) %>%
  left_join(image_dict, by=c("j"="images")) %>%
  select(-j) %>%
  rename(j = image_num) %>%
  left_join(image_dict, by=c("k"="images")) %>%
  select(-k) %>%
  rename(k = image_num)
```

Save for python
```{r, eval = F}
write.csv(d_numeric, "triplet_data.csv", row.names = F)
```

Run get_embeddings.ipynb to get embeddings (computeEmbeddings python)
`jupyter notebook get_embeddings.ipynb`.

### Read in embeddings
```{r}
es = read.csv("mid_embed.csv", header = F) 
colnames(es) = c("X", "Y")

es = cbind(images, es) # add image names
```

### Plot
```{r}
ggplot(es, aes(x = X, y = Y)) +
   geom_text(aes(label=images)) +
   theme_void()
```